/**
 * resolve-tokens.js — Pathway Design System token resolver
 *
 * Converts a semantic token ID (e.g. "Fill/Contextual/NavItem/Base") and a
 * theme ("light" | "dark") to the resolved CSS color value.
 *
 * Data source: src/tokens/tokens.js (generated by Style Dictionary from
 * tokens/pathway-design-tokens.json — do not edit that file by hand).
 *
 * tokens.js is emitted in DTCG nested format:
 *   { "semantic-color": { "light-mode": { "fill": { ... "$value": "#hex" } } } }
 * This module flattens it at load time into the keyed map resolve-tokens expects.
 *
 * Usage (ES module / Storybook / Vite):
 *   import { t } from "../../tokens/resolve-tokens.js";
 *   const color = t("Fill/Contextual/NavItem/Base");         // light by default
 *   const dark  = t("Fill/Contextual/NavItem/Base", "dark");
 *
 * Usage (Babel standalone HTML — add before <script type="text/babel">):
 *   <script src="../../tokens/resolve-tokens.js"></script>
 *   // window.t and window.resolveToken are set automatically.
 */

import rawTokens from "../src/tokens/tokens.js";

/**
 * Flatten nested DTCG token object into a keyed map.
 *
 * Input:  { "semantic-color": { "light-mode": { "fill": { ... "$value": "#hex" } } } }
 * Output: { "semantic-color-light-mode-fill-...": { value: "#hex" } }
 *
 * Leaf nodes are identified by the presence of "$value" or "value".
 */
function flattenTokens(obj, prefix = "") {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}-${key}` : key;
    if (val && typeof val === "object") {
      if ("$value" in val) {
        result[fullKey] = { value: val.$value };
      } else if ("value" in val) {
        result[fullKey] = { value: val.value };
      } else {
        Object.assign(result, flattenTokens(val, fullKey));
      }
    }
  }
  return result;
}

const tokens = flattenTokens(rawTokens);

// Build the flat key from a display-format token ID.
// "Fill/Contextual/NavItem/Base" + "light" →
//   "semantic-color-light-mode-fill-contextual-navitem-base"
//
// Segment normalisation: lowercase, then for segments with spaces try
// space→hyphen first (e.g. "Secondary Inverse" → "secondary-inverse"),
// then space→empty (e.g. "NavItem" → "navitem" via no-op since no spaces).
function buildKey(id, themeKey) {
  const segments = id.split("/").map(s => s.toLowerCase());

  function trySegments(idx, parts) {
    if (idx === segments.length) {
      const key = `semantic-color-${themeKey}-${parts.join("-")}`;
      return key in tokens ? key : null;
    }
    const seg = segments[idx];
    const variants = seg.includes(" ")
      ? [seg.replace(/\s+/g, "-"), seg.replace(/\s+/g, "")]
      : [seg];
    for (const v of variants) {
      const result = trySegments(idx + 1, [...parts, v]);
      if (result !== null) return result;
    }
    return null;
  }

  return trySegments(0, []);
}

const cache = new Map();

/**
 * Resolve a semantic token ID to its CSS color value.
 * Returns the token ID unchanged if no match is found.
 */
export function t(id, theme = "light") {
  const themeKey = theme.includes("-") ? theme : `${theme}-mode`;
  const cacheKey = `${themeKey}:${id}`;
  if (cache.has(cacheKey)) return cache.get(cacheKey);
  const key = buildKey(id, themeKey);
  const value = key ? (tokens[key]?.value ?? id) : id;
  cache.set(cacheKey, value);
  return value;
}

export { t as resolveToken };

// Browser global — makes t() and resolveToken() available in plain <script> contexts
// (Babel standalone HTML) without requiring a bundler.
if (typeof globalThis !== "undefined" && typeof globalThis.window !== "undefined") {
  globalThis.t = t;
  globalThis.resolveToken = t;
}
